// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbvcdbbdstnlzycbkjxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNidmNkYmJkc3RubHp5Y2JranhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTY3NDUsImV4cCI6MjA2NTQ3Mjc0NX0.3PDLWvqKdb9pa8sScK6zUvFK1dhTmbCKsoFbKzvPNY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);